alias j=fasd_cd
alias v='f -e vim'
alias sed=gsed
alias vi="gvim -v"
alias gpg=gpg2
alias ls="/usr/local/bin/gls  --color"
alias ll='ls -l'
alias la='ls -a'
alias ..='cd ..'
alias ..='cd ...'
alias cuke=cucumber.js
alias g=grunt
alias gw=grunt watch
alias gkw=grunt karma:all:start watch
alias gc=grunt karma:cuke_me
alias arstunnel="ssh -L 5439:redshift-prod-1.cx1nsbwqjxwv.us-east-1.redshift.amazonaws.com:5439 ec2-54-85-158-4.compute-1.amazonaws.com -l will -N &"
alias greentunnel="ssh -L 5441:helixdwh-green-prod.cx1nsbwqjxwv.us-east-1.redshift.amazonaws.com:5439 ec2-54-85-158-4.compute-1.amazonaws.com -l will -N &"
alias bluetunnel="ssh -L 5440:helixdwh-blue-prod.cx1nsbwqjxwv.us-east-1.redshift.amazonaws.com:5439 ec2-54-85-158-4.compute-1.amazonaws.com -l will -N &"
alias less='less -r'
alias more=less
