-- local lsp_zero = require('lsp-zero')
-- require('mason').setup({})
-- require('mason-lspconfig').setup({
--   ensure_installed = { 'tsserver', 'lua_ls', 'vimls', 'cssls' }
-- })
-- local nullls = require('null-ls')
-- local formatting = nullls.builtins.formatting
-- nullls.setup({
--   sources = { formatting.prettierd }
-- })
